Repository rainlab/pages-plugin, pull requests merged in 2021-03, with the labels that each got.

#468 Improve page loading performance
  classes/PageList.php
Labels: Status: Review Needed, Type: Maintenance

#454 Add the pages.snippets.listSnippets event
  classes/SnippetManager.php
  docs/documentation.md
Labels: Status: Accepted, Status: Testing Needed, Type: Conceptual Enhancement

#450 Add type property to staticMenu component items
  classes/Menu.php
  classes/MenuItemReference.php
Labels: Status: Revision Needed, Type: Maintenance
